EdotNet/Models/Utilisateur.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Net;

namespace Copie0Web.Models
{
    public class Utilisateur
    {
        [Key]
        public int Id { get; set; }
     
        [Required(ErrorMessage = "Votre Nom est requis !")]
        public string Nom { get; set; }
        [Required(ErrorMessage = "Votre prénom est requis !")]
        public string Prenom { get; set; }
        //[Required]
        //[DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateNaissance { get; set; }
        //[Required(ErrorMessage = "Votre lieu de naissance est requis !")]
        public string LieuNaissance { get; set; }
        public string Nationalité { get; set; }
        //[Required(ErrorMessage ="Indiquer votre Niveau d'etudes !")]
        public Niveau NiveauEtude { get; set; }
        //[Required(ErrorMessage = "Indiquer votre situation actuelle !")]
        public Statut StatutActuel  { get; set; }
        //[Required(ErrorMessage = "Indiquer l'etat de votre diplome !")]
        public  StatutDiplome Diplome  { get; set; }
        //[Required]
        public StatutCategorie Catégorie { get; set; }
        //[Required(ErrorMessage = "JOindre votre CV!;")]
        public string CV { get; set; }
        //[Required(ErrorMessage = "Votre Adresse est requise !")]
        public string Adresse { get; set; }
        public string ComplementAdresse { get; set; }
        //[Required(ErrorMessage = "Le Code Postal est requis !")]
        public int CodePostal { get; set; }
        //[Required(ErrorMessage = "La Ville est requise !")]
        public string Ville { get; set; }

        //[Required(ErrorMessage = "Merci d'indiquer votre numéro de téléphone")]
        public int TelephoneMobile { get; set; }
        public string IdIdentityFramework { get; internal set; }
        
    }

    public enum Statut
    {
        Selectionner ,
        DemandeurEmploi,
        Salarier,
        Entrepreneur,
        Particulier

    };
    public enum StatutDiplome
    {
        Selectionner,
        Obtenu,
        Encours,
        NonObtenu


    };
    public enum StatutCategorie
    {
        Selectionner,
        sansAllocations,
        RSA,
        AllocationAssédic,
        Autre

    };
    public enum Niveau
    {
        Selectionner,
        CAP ,
        BEP,
        Baccalauréat ,
        DEUG ,
        BTS,
        DUT,
        DEUST,

        Licence, 
        LicenceLMD, 
        licenceprofessionnelle,
        Maîtrise ,
        Master, 
        DEA, 
        DESS,
        diplômeIngénieur
        
                        
    };
}

EdotNet/Controllers/UtilisateursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Copie0Web.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Copie0Web.Controllers
{
    public class UtilisateursController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public List<string> SessionCours { get; private set; }


        // GET: Utilisateurs
        public async Task<ActionResult> Index()
        {
            return View(await db.Utilisateurs.ToListAsync());
        }

        // GET: Utilisateurs/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Utilisateur utilisateur = await db.Utilisateurs.FindAsync(id);
            if (utilisateur == null)
            {
                return HttpNotFound();
            }
            return View(utilisateur);
        }
        //Espace Formateur Get 
        public ActionResult EspaceFormateur()
        {
            string IdIdentityFramework = System.Web.HttpContext.Current.User.Identity.GetUserId();
            Utilisateur utilisateur = db.Utilisateurs.Where(u => u.IdIdentityFramework == IdIdentityFramework).First();
            Session["formateur"] = utilisateur;
            List<Module> _list = new List<Module>();
            
            var result = (from elt in db.Modules

                          where elt.NomFormateur == utilisateur.Prenom
                          select elt
                        ).ToList();
            List<Module> _list1 = result.ToList();
            Session["module"] = _list1;

            List<string> items = GetFiles();

            return View(items);
        }

        // Espace Formateur :
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult EspaceFormateur(HttpPostedFileBase file)
        {
            //telecharger les documents
            if (file != null && file.ContentLength > 0)
            {
                try
                {
                    string path = Path.Combine(Server.MapPath("~/Cours"),
                                               Path.GetFileName(file.FileName));
                    file.SaveAs(path);
                    ViewBag.Message = "File uploaded successfully";
                }
                catch (Exception ex)
                {
                    ViewBag.Message = "ERROR:" + ex.Message.ToString();
                }
            }
            else
            {
                ViewBag.Message = "Aucun fichier telechargé ";
            }

            var items = GetFiles();
         
      
            return View("EspaceFormateur",items);
          
        }

        public FileResult Download(string DocName)
        {
            var FileVirtualPath = "~/Cours/" + DocName;
            return File(FileVirtualPath, "application/force- download", Path.GetFileName(FileVirtualPath));
        }

        private List<string> GetFiles()
        {
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/Cours"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*");

            List<string> items = new List<string>();
            foreach (var file in fileNames)
            {
                items.Add(file.Name);
            }

            return items;
        }




        //GET
        //espace Stagiaire 
        public ActionResult EspaceStagiaire()
        {
            if (Request.IsAuthenticated)
            {
                string IdIdentityFramework = System.Web.HttpContext.Current.User.Identity.GetUserId();
                Utilisateur utilisateur = db.Utilisateurs.Where(u => u.IdIdentityFramework == IdIdentityFramework).First();

                //IList<Inscription> inscription = db.Inscriptions.Where(p => p.Utilisateur.Id == utilisateur.Id).ToList();
                Session["Stagiaire"] = utilisateur;
                //var rm = new Microsoft.AspNet.Identity.RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new ApplicationDbContext()));
                //var um = new Microsoft.AspNet.Identity.UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext())) ;
               
                IList<Inscription> list1 = new List<Inscription>();

                List<Inscription> result = (from elt in db.Inscriptions
                                            where (elt.Utilisateur.Id == utilisateur.Id)
                                            select elt).ToList();
                list1 = result;


                Session["inscription"] = list1;

                    // return RedirectToAction("Details", "Inscriptions",inscription);
                   return View(list1);
               }
            //else

                

            //if (inscription != null)
            //{
            //    return View(inscription);

            //}

            return View();
        }
       
        //Get Candidature 
        public ActionResult Candidature()
        {
          

            if (Request.IsAuthenticated)
            {
               
                string IdIdentityFramework = System.Web.HttpContext.Current.User.Identity.GetUserId();
                Utilisateur utilisateur = db.Utilisateurs.Where(u => u.IdIdentityFramework == IdIdentityFramework).First();
                Inscription inscription = db.Inscriptions.Where(p => p.Utilisateur.Id == utilisateur.Id).FirstOrDefault();
                List<Cursus> _list = (List<Cursus>)Session["cursus"];

                if (_list != null)
                {

                    inscription.Parcours = new List<Cursus>();
                    for (int i = 0; i < _list.Count(); i++)
                    {
                        Cursus cursus = new Cursus
                        {
                            Id = _list[i].Id,
                            Titre = _list[i].Titre,
                            IdSession = _list[i].IdSession,
                            Image = _list[i].Image,
                            DateDebut = _list[i].DateDebut,
                            DateFin = _list[i].DateFin
                        };
                        inscription.Parcours.Add(cursus);
                        inscription.Utilisateur = utilisateur;
                    }


                    inscription.DateInscription = DateTime.Now;
                    db.Inscriptions.Add(inscription);
                    db.SaveChanges();


                    return RedirectToAction("Details", "Inscriptions",inscription);
                }
               
            }
            return RedirectToAction("Index","Home");
        }
        // GET: Utilisateurs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Utilisateurs/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nom,Prenom,DateNaissance,LieuNaissance,Nationalité,NiveauEtude,StatutActuel,Diplome,Catégorie,Adresse,ComplementAdresse,CodePostal,Ville,TelephoneMobile")] Utilisateur utilisateur, HttpPostedFileBase CV)
        {
            if (ModelState.IsValid)
            {
                if (CV.ContentLength > 0)
                    {
                        string fileName = Path.GetFileName(CV.FileName);
                        string filePath = Path.Combine(Server.MapPath("/CV/"), fileName);
                        CV.SaveAs(filePath);
                         utilisateur.CV = filePath;
                    }
              
                utilisateur.IdIdentityFramework = System.Web.HttpContext.Current.User.Identity.GetUserId();
                db.Utilisateurs.Add(utilisateur);

                db.SaveChanges();
                Session["Utilisateur"] = utilisateur;
                List<Cursus> _list = (List<Cursus>)Session["cursus"];

                if (_list != null)
                {
                    Inscription inscription = new Inscription();
                    inscription.Parcours = new List<Cursus>();
                    for (int i = 0; i < _list.Count(); i++)
                    {
                        Cursus cursus = new Cursus();

                        cursus.Id = _list[i].Id;
                        cursus.Titre = _list[i].Titre;
                        cursus.IdSession = _list[i].IdSession;
                        cursus.Image = _list[i].Image;
                        cursus.DateDebut = _list[i].DateDebut;
                        cursus.DateFin = _list[i].DateFin;
                        inscription.Parcours.Add(cursus);
                        inscription.Utilisateur = utilisateur;
                    }


                    inscription.DateInscription = DateTime.Now;
                    db.Inscriptions.Add(inscription);

                    Session["InscriptionCursus"] = inscription;
                    db.SaveChanges();
                
       
                    return RedirectToAction("Details" ,"Inscriptions", inscription);
                }
                List<Module> _list1 = (List<Module>)Session["module"];
                if (_list1 != null)
                {
                    Inscription inscription = new Inscription();
                    inscription.Modules = new List<Module>();
                    for (int i = 0; i < _list1.Count(); i++)
                    {
                        Module module = new Module();

                        module.Id = _list1[i].Id;

EdotNet/Views/Utilisateurs/Create.cshtml
@model Copie0Web.Models.Utilisateur

@{
    //ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <center><h2><strong> Nouvelle Inscription</strong></h2></center>
 @using (Html.BeginForm("Create", "Utilisateurs", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
              
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Prenom, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Prenom, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Prenom, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateNaissance, new { htmlAttributes = new { @class = "date" } })
                        @Html.ValidationMessageFor(model => model.DateNaissance, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LieuNaissance, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.LieuNaissance, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LieuNaissance, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Nationalité, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Nationalité, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Nationalité, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NiveauEtude, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.NiveauEtude, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.NiveauEtude, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StatutActuel, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.StatutActuel, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.StatutActuel, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Diplome, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Diplome, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Diplome, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Catégorie, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EnumDropDownListFor(model => model.Catégorie, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Catégorie, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CV, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.CV, new { type = "file" })
                        @Html.ValidationMessageFor(model => model.CV)
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Adresse, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Adresse, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Adresse, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ComplementAdresse, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ComplementAdresse, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ComplementAdresse, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CodePostal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CodePostal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CodePostal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Ville, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Ville, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ville, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TelephoneMobile, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TelephoneMobile, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TelephoneMobile, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>

        }
   
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EdotNet/Views/Utilisateurs/Delete.cshtml
@model Copie0Web.Models.Utilisateur

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        
    

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LieuNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LieuNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationalité)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationalité)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NiveauEtude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NiveauEtude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatutActuel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatutActuel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diplome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diplome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Catégorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catégorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComplementAdresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComplementAdresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodePostal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodePostal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelephoneMobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelephoneMobile)
        </dd>

      

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EdotNet/Views/Utilisateurs/Details.cshtml
@model Copie0Web.Models.Utilisateur

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Utilisateur</h4>
    <hr />
    <dl class="dl-horizontal">
        

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Prenom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LieuNaissance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LieuNaissance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nationalité)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nationalité)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NiveauEtude)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NiveauEtude)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StatutActuel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StatutActuel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diplome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diplome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Catégorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Catégorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ComplementAdresse)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ComplementAdresse)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodePostal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodePostal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ville)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ville)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TelephoneMobile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TelephoneMobile)
        </dd>

     

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EdotNet/Views/Utilisateurs/EspaceFormateur.cshtml
@{
    //ViewBag.Title = "Alex";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<br />
<div >
    <center><img src="~/images/logos/formateur2.jpeg" width="250px" /> </center>
        
 </div>
<div class="  container">
    <div class="container">
        <div class="row">
            <div class="col-6 text-left">

                @{
                    Copie0Web.Models.Utilisateur utilisateur = new Copie0Web.Models.Utilisateur();

                    if (Session["formateur"] != null)
                    {
                        utilisateur = (Session["formateur"] as Copie0Web.Models.Utilisateur);
                    }
                }
                <p>
                    <span>@utilisateur.Nom</span>
                </p>
                <p>
                    <span>@utilisateur.Prenom</span>
                </p>
                <p>
                    @utilisateur.Adresse
                </p>
                <p>
                    @utilisateur.CodePostal <span>@utilisateur.Ville</span>
                </p>
                <p>
                    @utilisateur.TelephoneMobile
                </p>
            </div>

        </div>
    </div>

    <br />

    <div class="container">
        <div class="row">
            <div class="col-12">
                <center><h1>Listes des Modules</h1></center>
                <br />
                @{
                    var NombreModules = 0;
                    if (Session["module"] != null)
                    {
                        NombreModules = (Session["module"] as List<Copie0Web.Models.Module>).Count();
                        IList<Copie0Web.Models.Module> list = new List<Copie0Web.Models.Module>();
                        list = (List<Copie0Web.Models.Module>)Session["module"];
                        for (int i = 0; i < NombreModules; i++)
                        {
                            <div class="col-md-4">
                                <div class="card" style="width: 18rem;">
                                    <img src="@Url.Content(@list[i].LogoModule)" alt="@list[i].Nom" width="100px" class="card-img-top" />
                                    <div class="card-body">
                                        <h5 class="card-title">@list[i].Nom</h5>
                                        <p class="card-text">
                                            <center>
                                                @list[i].DateDebut.ToShortDateString() <br /> @list[i].DateFin.ToShortDateString()
                                            </center>
                                        </p>
                                    </div>
                                </div>
                            </div>

                        }
                    }
                }

            </div>
        </div>
    </div>
    <br />
    <br />

    @model List<string>

    @using (Html.BeginForm("EspaceFormateur",
                            "Utilisateurs",
                            FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
    {



        <input type="file" name="file" id="file" />
        <br>
        <input type="submit" value="Télecharger " class="btn btn-primary" />
        <br>
        <br>
        <p>
            <img src="~/images/logos/telecharger.jpeg" width="150px" />
        </p>

        <table>

            @for (var i = 0; i <= Model.Count() - 1; i++)
            {
                <tr>
                    <td>@Model[i].ToString() </td>
                    <td></td>
                    <td>@Html.ActionLink("Télécharger", "Download", new { DocName = Model[i].ToString() }) </td>
                </tr>
            }
        </table>
    }
</div>
<br />
<br />