EdotNet/Models/Cursus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Copie0Web.Models
{
    public class Cursus
    {
        [Key]
        public int Id { get; set; }
        public int IdSession { get; set; }
        public string Titre { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateDebut { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateFin { get; set; }
        public string Image { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Module> Modules { get; set; }
        public virtual ICollection<Inscription> Inscriptions { get; set; }
       
    }

   
}

EdotNet/Controllers/CursusController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using Copie0Web.Models;
using System.Windows.Forms;
using System.Web;
using System.IO;
using AutoMapper;
using System;
using Microsoft.AspNet.Identity;

namespace Copie0Web.Controllers
{
    public class CursusController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        private IList<Cursus> Parcours = new List<Cursus>();
        

        ////Get: Listes de parcours 
        public ActionResult ListeParcours()
        {
            if (db.Cursus == null)
            {
                return HttpNotFound();
            }
            else
            {
              
                var list1 = db.Cursus.GroupBy(x => x.Titre).Select(y => y.FirstOrDefault()).ToList();
                return PartialView("ListeParcours", list1);
            }

        }
        public ActionResult ListeModulesParcours(int id)
        {
            List<Module> _list = db.Modules.Where(x => x.IdCursus == id).ToList();

            return PartialView("ListeModulesParcours", _list);
        }

        //Inscription
        //Get :Inscription 
        //private IList<Module> ModulePanier;
        //private IList<Module> SessiCursusPanier;
    //    public ActionResult AjoutModule(int? id )
    //    {
    //        if (id == null)
    //        {
    //            return RedirectToAction("ListeParcoursSessions", "Sessions");
    //        }
    //        Cursus cursus = db.Cursus.Find(id);

    //        if (Session["cursus"] == null)
    //        {
    //            CursusPanier = new List<Cursus>();
    //            Session["cursus"] = CursusPanier;
    //        }

    //        SessiCursusPanier = (List<Cursus>)Session["cursus"];
    //        SessiCursusPanier.Add(cursus);
    //        Session["cursus"] = SessiCursusPanier;

    //        List<Cursus> _list = (List<Cursus>)Session["cursus"];

    //        return PartialView("AjoutCursus", _list);

    //    }


    //}
        // GET: Cursus
        public async Task<ActionResult> Index()
        {
            return View(await db.Cursus.ToListAsync());
        }

        // GET: Cursus/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursus cursus = await db.Cursus.FindAsync(id);
            if (cursus == null)
            {
                return HttpNotFound();
            }
            return View(cursus);
        }

        // GET: Cursus/Create
        public ActionResult Create()
        {
            ViewBag.IdSession = new SelectList(db.Sessions, "Id", "Titre");
            return View();
        }

        // POST: Cursus/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,IdSession,Titre ,DateDebut,DateFin")]Cursus cursus , HttpPostedFileBase Image)
        {
           if (ModelState.IsValid)
            {

                if (Image != null && Image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Image.FileName);
                    var path = Path.Combine(("~/images/cursus/"), fileName);
                    //Image.SaveAs(path);
                
                    cursus.Image = path;
                }


                if (cursus.Image == null) cursus.Image = ".net.png";
                db.Cursus.Add(cursus);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(cursus);
        }
      
       
        // GET: Cursus/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursus cursus = await db.Cursus.FindAsync(id);
            if (cursus == null)
            {
                return HttpNotFound();
            }
            return View(cursus);
        }

        // POST: Cursus/Edit/
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdSession,Titre,,DateDebut,DateFin")] Cursus cursus , HttpPostedFileBase Image)
        {
            if (ModelState.IsValid)
            {
                if (Image != null && Image.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(Image.FileName);
                    var path = Path.Combine(("~/images/cursus/"), fileName);
                    //Image.SaveAs(path);
                    cursus.Image = path;
                }


                if (cursus.Image == null) cursus.Image = ".net.png";
                db.Entry(cursus).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(cursus);
        }

        // GET: Cursus/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursus cursus = await db.Cursus.FindAsync(id);
            if (cursus == null)
            {
                return HttpNotFound();
            }
            return View(cursus);
        }

        // POST: Cursus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Cursus cursus = await db.Cursus.FindAsync(id);
            db.Cursus.Remove(cursus);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EdotNet/Views/Cursus/Create.cshtml
@model Copie0Web.Models.Cursus

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Cursus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

 <div class="form-horizontal">
    <h4>Cursus</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.Sessions, "Sessions", htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.DropDownList("IdSession", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sessions, "", new { @class = "text-danger" })
            </div>
        </div>
    @*<div class="form-group">
        @Html.LabelFor(model => model.IdSession, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdSession, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdSession, "", new { @class = "text-danger" })
        </div>
     </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDebut, new { htmlAttributes = new { @class = "date" } })
                @Html.ValidationMessageFor(model => model.DateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class = "date" } })
                @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="file" name="Image" value=".net.png"
               onchange="document.getElementById('Image').src=window.URL.createObjectURL(this.files[0])" />
        <img id="Image" src="~/images/cursus/.net.png" class="img-fluid" width="150px" title="logo parcours" />
          
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    

EdotNet/Views/Cursus/Delete.cshtml
@model Copie0Web.Models.Cursus

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cursus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EdotNet/Views/Cursus/Details.cshtml
@model Copie0Web.Models.Cursus

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Cursus</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdSession)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdSession)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EdotNet/Views/Cursus/Edit.cshtml
@model Copie0Web.Models.Cursus

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Cursus", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cursus</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdSession, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdSession, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdSession, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="file" name="Image" value="~/images/cursus/@Html.DisplayFor(modelItem => modelItem.Image)"
                   onchange="document.getElementById('logoParcours').src=window.URL.createObjectURL(this.files[0])" />
            <img id="logoParcours" src="~/images/cursus/@Html.DisplayFor(modelItem => modelItem.Image)" class="img-fluid" width="150px" title="logo parcours" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EdotNet/Views/Cursus/Index.cshtml
@model IEnumerable<Copie0Web.Models.Cursus>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Ajouter Cursus", "Create", null, new { @class = "btn btn-outline-primary" })
  
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdSession)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Image)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdSession)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>
                <h6>
                    @Html.DisplayFor(modelItem => item.Titre)
                </h6>
                <span>
                    <img src="@Url.Content(@item.Image)" alt="@item.Titre"  width="60px"/>
                    @*<img src="@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" width="60px" title="@Html.DisplayFor(modelItem => item.Titre)" />*@
                   
                </span>
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EdotNet/Views/Cursus/ListeModulesParcours.cshtml
@model IEnumerable<Copie0Web.Models.Module>

@{
    //ViewBag.Title = "ListeModulesParcours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <center>
        <h1> Les Modules du parcours </h1>
    </center>
</p>
<div>
    <div class="container">
        <div class="row">

            @foreach (var item in Model)

            {


                <div class="col-md-4">
                    <div class="card border-primary mb-3" style="width: 18rem;">
                        <img src="@Url.Content(@item.LogoModule)" class="img-fluid" width="150px" alt="@Html.DisplayFor(modelItem => item.LogoModule)" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">@item.Nom</h5>
                            <button type="button" id="@item.Id"
                                    class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="bottom" data-content=" Module:@item.Nom ; Nom de Formateur:@item.NomFormateur ; Nombre d'heures :@item.NombreHeures">
                                Details
                                <script>
                            $('#@item.Id').popover({
                            trigger: 'focus'
                            });
                                </script>

                            </button>

                            @*<a href="~/Sessions/AjoutModule/@item.Id" class="btn btn-info">Choisir</a>*@
                        </div>

                    </div>
                </div>
                <br />

            }

        </div>
        <hr />
    </div>
</div>

EdotNet/Views/Cursus/ListeParcours.cshtml
@model IEnumerable<Copie0Web.Models.Cursus>

@{
    ViewBag.Title = "ListeParcours";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<p>
    <center>
        <h1> Les Parcours disponibles </h1>
    </center>
</p>
<table class="table">
    <thead class="thead-light">
        <tr>
            @*<th scope="col">Session</th>*@
            <th scope="col"> Nom de Parcours</th>
            <th scope="col">Parcours</th>



        </tr>

    </thead>


    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Titre)
            </td>
            <td>

                <h6>
                    @Html.DisplayFor(modelItem => item.Titre)
                </h6>
                <span>

                    <img src="@Url.Content(@item.Image)" class="img-fluid" width="150px" title=" @Html.DisplayFor(modelItem => item.Titre)" />
                </span>
            </td>
            <td>

            <td>

                <button type="button" class="btn btn-info">

                    @Html.ActionLink("Modules", "ListeModulesParcours", new { id = item.Id })
                </button>
             
                    <a href="~/Sessions/AjoutCursus/@item.Id" class="btn btn-info">Choisir</a>
            </td>

        </tr>
    }

</table>
<hr />
<button type="button" class="btn btn-info">
    @Html.ActionLink("Session", "ListeSessions")
</button>