EdotNet/Models/Module.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Copie0Web.Models
{
    public class Module
    {
        [Key]
        public int Id { get; set; }
        public int IdCursus { get; set; }
        public string Nom { get; set; }
        //public string Description { get; set; }
        public int NombreHeures { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateDebut { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateFin { get; set; }
        public string LogoModule { get; set; }
        public string NomFormateur { get; set; }
        public virtual ICollection<Cursus> Parcours { get; set; }
        public virtual ICollection<Inscription> Inscriptions { get; set; }
       //public virtual Utilisateur Utilisateur { get; set; }


    }
}

EdotNet/Controllers/ModulesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Copie0Web.Models;
using System.IO;
using System.Web.Helpers;

namespace Copie0Web.Controllers
{
    public class ModulesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Modules
        public async Task<ActionResult> Index()
        {
            return View(await db.Modules.ToListAsync());
        }

        // GET: Modules/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        public ActionResult ListeModules()
        {
            if (db.Modules == null)
            {
                return HttpNotFound();
            }
            else
            {
                return PartialView("ListeModules", db.Modules.ToList());
            }

        }
        // GET: Modules/Create
        public ActionResult Create()
        {
            ViewBag.IdCursus = new SelectList(db.Cursus, "Id", "Titre");
            return View();
            
        }

        // POST: Modules/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,IdCursus,Nom,NombreHeures,DateDebut,DateFin,NomFormateur")] Module module, HttpPostedFileBase LogoModule)
        {
            if (ModelState.IsValid)
            {
                if (LogoModule != null && LogoModule.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(LogoModule.FileName);
                    string path = Path.Combine(("~/images/modules/"), fileName);

                    //LogoModule.SaveAs(path);
                    module.LogoModule = path;
                }
                if (module.LogoModule == null) module.LogoModule = "agile.png";
                db.Modules.Add(module);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(module);
        }

        // GET: Modules/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Modules/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,IdCursus,Nom,NombreHeures,DateDebut,DateFin,NomFormateur")] Module module, HttpPostedFileBase LogoModule)
        {
            if (ModelState.IsValid)
            {
                if (module.LogoModule != null && module.LogoModule.Length > 0)
                {
                    string fileName = Path.GetFileName(LogoModule.FileName);
                    string path = Path.Combine("~/images/modules/", fileName);

                    //LogoModule.SaveAs(path);
                    module.LogoModule = path;
                }
                if (module.LogoModule == null) module.LogoModule = "aspNet.png";
                db.Entry(module).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(module);
        }

        // GET: Modules/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Modules/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Module module = await db.Modules.FindAsync(id);
            db.Modules.Remove(module);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EdotNet/Views/Modules/Create.cshtml
@model Copie0Web.Models.Module

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Modules", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Module</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        <div class="col-md-10">
            @Html.LabelFor(model => model.Parcours, "Cursus", htmlAttributes: new { @class = "control-label col-md-2" })
            @Html.DropDownList("IdCursus", null, htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.IdCursus, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.ValidationMessageFor(model => model.Parcours, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            @Html.LabelFor(model => model.IdCursus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCursus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCursus, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NombreHeures, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NombreHeures, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NombreHeures, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateDebut, new { htmlAttributes = new { @class ="date" } })
            @Html.ValidationMessageFor(model => model.DateDebut, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class ="date" } })
            @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomFormateur, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomFormateur, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomFormateur, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LogoModule, htmlAttributes: new { @class = "control-label col-md-2" })
        @*<input type="file" name="Image" />
            <img src="@imagePath" alt="image" />*@

        @Html.LabelFor(model => model.LogoModule, htmlAttributes: new { @class = "control-label col-md-2" })
        <input type="file" name="logoModule" value="agile.png"
               onchange="document.getElementById('logoModule').src=window.URL.createObjectURL(this.files[0])" />

        <img id="logoModule" src="~/images/modules/agile.png" class="img-fluid" width="150px" title="logo module" />


    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EdotNet/Views/Modules/Delete.cshtml
@model Copie0Web.Models.Module

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCursus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCursus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        @*<dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>*@
        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreHeures)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreHeures)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomFormateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomFormateur)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LogoModule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogoModule)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EdotNet/Views/Modules/Details.cshtml
@model Copie0Web.Models.Module

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Module</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCursus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCursus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nom)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nom)
        </dd>
        @*<dd>
            @Html.DisplayFor(model => model.Description)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.NombreHeures)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreHeures)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateDebut)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateDebut)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateFin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomFormateur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomFormateur)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LogoModule)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LogoModule)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EdotNet/Views/Modules/Edit.cshtml
@model Copie0Web.Models.Module

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Modules", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Module</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.IdCursus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IdCursus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdCursus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nom, "", new { @class = "text-danger" })
            </div>
        </div>
        @*<div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.NombreHeures, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NombreHeures, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NombreHeures, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateDebut, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateDebut, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateDebut, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateFin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateFin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateFin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NomFormateur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomFormateur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomFormateur, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LogoModule, htmlAttributes: new { @class = "control-label col-md-2" })
            <input type="file" name="Image" value="default_image.png"
                   onchange="document.getElementById('logoModule').src=window.URL.createObjectURL(this.files[0])" />
            <img id="logoModule" src="~/images/modules/agile.png" class="img-fluid" width="150px" title="logo parcours" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EdotNet/Views/Modules/Index.cshtml
@model IEnumerable<Copie0Web.Models.Module>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCursus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nom)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Description)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.NombreHeures)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateDebut)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateFin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomFormateur)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LogoModule)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.IdCursus)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Nom)
    </td>
    @*<td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>*@
    <td>
        @Html.DisplayFor(modelItem => item.NombreHeures)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateDebut)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.DateFin)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.NomFormateur)
    </td>
    <td>
        @*@Html.DisplayFor(modelItem => item.LogoModule)*@
        <h6>
            @Html.DisplayFor(modelItem => item.Nom)
        </h6>
        <span>
            <img src="@Url.Content(@item.LogoModule)" alt="@item.Nom" width="60px" />
        </span>
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>
    }

</table>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EdotNet/Views/Modules/ListeModules.cshtml
@model IEnumerable<Copie0Web.Models.Module>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.0/jquery.min.js"
        integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ=" crossorigin="anonymous">
</script>


<!-- Bootstrap CSS -->
@*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">*@

<!-- Optional JavaScript -->
<!-- Popper.js, then Bootstrap JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

@{
    ViewBag.Title = "ListeModules";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    <center>
        <h1> Les Modules Disponibles </h1>
    </center>
</p>

<div>
    <div class="container">
        <div class="row">

            @foreach (var item in Model)

            {
                <div class="col-md-4">
                    <div class="card" style="width: 18rem;">
                        <img src="@Url.Content(@item.LogoModule)" alt="@item.Nom" width="100px" class="card-img-top" />
                        <div class="card-body">
                            <h5 class="card-title">@item.Nom</h5>
                            <p class="card-text">
                                <center>
                                    @item.DateDebut.ToShortDateString() -- @item.DateFin.ToShortDateString() <hr />

                                </center>
                            </p>

                            @*<a tabindex="0" class="btn btn-lg btn-danger" role="button" data-toggle="popover" data-trigger="focus" title="Dismissible popover" data-content="And here's some amazing content. It's very engaging. Right?">Dismissible popover</a>*@
                            @*<button class="btn btn-info">
                                @Html.ActionLink("Chapitres", "Details", new { id = item.Id })*@
                        @*<button type="button" id="@item.Id"
                                class="btn btn-secondary" data-container="body" data-toggle="popover" data-placement="bottom" data-content="@item.Nom  @item.NomFormateur  @item.NombreHeures">
                            Details*@
                        <script>
                                @*$('.@item.Id').popover({
                            trigger: 'focus'
                            });*@
                                $('#@item.Id').popover({
                                    trigger: 'focus'
                                })
                        </script>
                            <a   tabindex="0" class="btn btn-lg btn-danger" role="button" data-toggle="popover" data-trigger="focus" title="Details" data-content="@item.Nom @item.NomFormateur  @item.NombreHeures">Details</a>

                        @*</button>*@


                        </div>
                    </div>
                </div>

            }
            <br />
        </div>
        <hr />
    </div>
</div>

@*@Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}